var PaneConstants = {
    START_HOLE : [0,0],
    ACTION_SET_IMAGE : 'PANE_SET_IMAGE',
    ACTION_SET_MATRIX : 'PANE_SET_MATRIX',
    ACTION_GAME_START : 'PANE_GAME_START',
    ACTION_GAME_ROLLBACK : 'PANE_GAME_ROLLBACK'
};

module.exports = PaneConstants;